# Generated by Django 5.0.1 on 2024-01-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripSplit', '0002_remove_trip_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
